apiVersion: apps/v1
kind: Deployment
metadata:
  name: nano35-repairorders-api
  namespace: nano35
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nano35-repairorders-api
  template:
    metadata:
      labels:
        app: nano35-repairorders-api
    spec:
      containers:
        - name: nano35-repairorders-api
          image: bushemi2021/nano35.repairorders.api:latest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nano35-repairorders-processor
  namespace: nano35
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nano35-repairorders-processor
  template:
    metadata:
      labels:
        app: nano35-repairorders-processor
    spec:
      containers:
        - name: nano35-repairorders-processor
          image: bushemi2021/nano35.repairorders.processor:latest
---
apiVersion: v1
kind: Service
metadata:
  name: nano35-repairorders-entrypoint
  namespace: nano35
spec:
  type: NodePort
  selector:
    app: nano35-repairorders-api
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30101