apiVersion: apps/v1
kind: Deployment
metadata:
  name: nano35-repair-orders-processor
  namespace: nano35
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nano35-repair-orders-processor
  template:
    metadata:
      labels:
        app: nano35-repair-orders-processor
    spec:
      containers:
      - image: bushemi2021/nano35.repair-orders.processor:latest
        name: nano35-repair-orders-processor
        ports:
        - containerPort: 80
      restartPolicy: Always